modLoader = "javafml"
loaderVersion = "[36,)"
license = "MIT"

[[mods]]
modId = "extrawarp"
version = "${project_version}"
displayName = "${project_name}"
logoFile = "logo.png"
authors = "Vecoo"
description = "Mod adding warp system."

[[dependencies.extrawarp]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.extrawarp]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.extrawarp]]
modId = "extralib"
mandatory = true
versionRange = "[1.8,)"
ordering = "NONE"
side = "BOTH"